### ISSUE TITLE
--show-skipped in ADO PR comment

### ISSUE THREAD

**Issue by mjazwiecki** [infracost/infracost-azure-devops#1]
hello,
is there a way to turn on --show-skipped and have the results posted along the cost estimate in PR comment?

**Comment by alikhajeh1** [comment]
@mjazwiecki I merged [a new PR](https://github.com/infracost/infracost/pull/850) just now to enable this :) 
Can you please add the `show_skipped=true` environment var to your `azure-pipelines.yml` and see if that works ok for you?
Since the pipeline fetches `curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh` it should work without other changes.

**Comment by mjazwiecki** [comment]
perfect, thanks - it works!

**Comment by alikhajeh1** [comment]
Awesome! I updated the docs https://github.com/infracost/infracost-azure-devops/pull/2
